name: excelmanage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.1.0
  excel: ^4.0.6
  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/